root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-config", "cmd/sps_mission/spsmission.config.yaml"]
  bin = "./tmp/sps_mission"
  cmd = "go build -o ./tmp/sps_mission ./cmd/sps_mission"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlinks = false
  full_bin = ""
  include_dir = ["cmd/sps_mission", "pkg/missionsdk"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  include_file = []
  kill_delay = "500ms"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
