// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/api/v1/task.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "vantageos-core/proto/api/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "api.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceCreateTaskProcedure is the fully-qualified name of the TaskService's CreateTask RPC.
	TaskServiceCreateTaskProcedure = "/api.v1.TaskService/CreateTask"
	// TaskServiceFindTaskProcedure is the fully-qualified name of the TaskService's FindTask RPC.
	TaskServiceFindTaskProcedure = "/api.v1.TaskService/FindTask"
	// TaskServiceListTasksProcedure is the fully-qualified name of the TaskService's ListTasks RPC.
	TaskServiceListTasksProcedure = "/api.v1.TaskService/ListTasks"
)

// TaskServiceClient is a client for the api.v1.TaskService service.
type TaskServiceClient interface {
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	FindTask(context.Context, *connect.Request[v1.FindTaskRequest]) (*connect.Response[v1.FindTaskResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
}

// NewTaskServiceClient constructs a client for the api.v1.TaskService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_proto_api_v1_task_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+TaskServiceCreateTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		findTask: connect.NewClient[v1.FindTaskRequest, v1.FindTaskResponse](
			httpClient,
			baseURL+TaskServiceFindTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("FindTask")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+TaskServiceListTasksProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	createTask *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	findTask   *connect.Client[v1.FindTaskRequest, v1.FindTaskResponse]
	listTasks  *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
}

// CreateTask calls api.v1.TaskService.CreateTask.
func (c *taskServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// FindTask calls api.v1.TaskService.FindTask.
func (c *taskServiceClient) FindTask(ctx context.Context, req *connect.Request[v1.FindTaskRequest]) (*connect.Response[v1.FindTaskResponse], error) {
	return c.findTask.CallUnary(ctx, req)
}

// ListTasks calls api.v1.TaskService.ListTasks.
func (c *taskServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the api.v1.TaskService service.
type TaskServiceHandler interface {
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	FindTask(context.Context, *connect.Request[v1.FindTaskRequest]) (*connect.Response[v1.FindTaskResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_proto_api_v1_task_proto.Services().ByName("TaskService").Methods()
	taskServiceCreateTaskHandler := connect.NewUnaryHandler(
		TaskServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceFindTaskHandler := connect.NewUnaryHandler(
		TaskServiceFindTaskProcedure,
		svc.FindTask,
		connect.WithSchema(taskServiceMethods.ByName("FindTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListTasksHandler := connect.NewUnaryHandler(
		TaskServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceCreateTaskProcedure:
			taskServiceCreateTaskHandler.ServeHTTP(w, r)
		case TaskServiceFindTaskProcedure:
			taskServiceFindTaskHandler.ServeHTTP(w, r)
		case TaskServiceListTasksProcedure:
			taskServiceListTasksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TaskService.CreateTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) FindTask(context.Context, *connect.Request[v1.FindTaskRequest]) (*connect.Response[v1.FindTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TaskService.FindTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TaskService.ListTasks is not implemented"))
}
