// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/api/v1/telemetry.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "vantageos-core/proto/api/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryServiceName is the fully-qualified name of the TelemetryService service.
	TelemetryServiceName = "api.v1.TelemetryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryServiceQueryTelemetryProcedure is the fully-qualified name of the TelemetryService's
	// QueryTelemetry RPC.
	TelemetryServiceQueryTelemetryProcedure = "/api.v1.TelemetryService/QueryTelemetry"
	// TelemetryServiceGetTelemetryStatusProcedure is the fully-qualified name of the TelemetryService's
	// GetTelemetryStatus RPC.
	TelemetryServiceGetTelemetryStatusProcedure = "/api.v1.TelemetryService/GetTelemetryStatus"
)

// TelemetryServiceClient is a client for the api.v1.TelemetryService service.
type TelemetryServiceClient interface {
	QueryTelemetry(context.Context, *connect.Request[v1.QueryTelemetryRequest]) (*connect.Response[v1.QueryTelemetryResponse], error)
	GetTelemetryStatus(context.Context, *connect.Request[v1.GetTelemetryStatusRequest]) (*connect.Response[v1.GetTelemetryStatusResponse], error)
}

// NewTelemetryServiceClient constructs a client for the api.v1.TelemetryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryServiceMethods := v1.File_proto_api_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	return &telemetryServiceClient{
		queryTelemetry: connect.NewClient[v1.QueryTelemetryRequest, v1.QueryTelemetryResponse](
			httpClient,
			baseURL+TelemetryServiceQueryTelemetryProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("QueryTelemetry")),
			connect.WithClientOptions(opts...),
		),
		getTelemetryStatus: connect.NewClient[v1.GetTelemetryStatusRequest, v1.GetTelemetryStatusResponse](
			httpClient,
			baseURL+TelemetryServiceGetTelemetryStatusProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("GetTelemetryStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryServiceClient implements TelemetryServiceClient.
type telemetryServiceClient struct {
	queryTelemetry     *connect.Client[v1.QueryTelemetryRequest, v1.QueryTelemetryResponse]
	getTelemetryStatus *connect.Client[v1.GetTelemetryStatusRequest, v1.GetTelemetryStatusResponse]
}

// QueryTelemetry calls api.v1.TelemetryService.QueryTelemetry.
func (c *telemetryServiceClient) QueryTelemetry(ctx context.Context, req *connect.Request[v1.QueryTelemetryRequest]) (*connect.Response[v1.QueryTelemetryResponse], error) {
	return c.queryTelemetry.CallUnary(ctx, req)
}

// GetTelemetryStatus calls api.v1.TelemetryService.GetTelemetryStatus.
func (c *telemetryServiceClient) GetTelemetryStatus(ctx context.Context, req *connect.Request[v1.GetTelemetryStatusRequest]) (*connect.Response[v1.GetTelemetryStatusResponse], error) {
	return c.getTelemetryStatus.CallUnary(ctx, req)
}

// TelemetryServiceHandler is an implementation of the api.v1.TelemetryService service.
type TelemetryServiceHandler interface {
	QueryTelemetry(context.Context, *connect.Request[v1.QueryTelemetryRequest]) (*connect.Response[v1.QueryTelemetryResponse], error)
	GetTelemetryStatus(context.Context, *connect.Request[v1.GetTelemetryStatusRequest]) (*connect.Response[v1.GetTelemetryStatusResponse], error)
}

// NewTelemetryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryServiceHandler(svc TelemetryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryServiceMethods := v1.File_proto_api_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	telemetryServiceQueryTelemetryHandler := connect.NewUnaryHandler(
		TelemetryServiceQueryTelemetryProcedure,
		svc.QueryTelemetry,
		connect.WithSchema(telemetryServiceMethods.ByName("QueryTelemetry")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceGetTelemetryStatusHandler := connect.NewUnaryHandler(
		TelemetryServiceGetTelemetryStatusProcedure,
		svc.GetTelemetryStatus,
		connect.WithSchema(telemetryServiceMethods.ByName("GetTelemetryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.TelemetryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryServiceQueryTelemetryProcedure:
			telemetryServiceQueryTelemetryHandler.ServeHTTP(w, r)
		case TelemetryServiceGetTelemetryStatusProcedure:
			telemetryServiceGetTelemetryStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryServiceHandler struct{}

func (UnimplementedTelemetryServiceHandler) QueryTelemetry(context.Context, *connect.Request[v1.QueryTelemetryRequest]) (*connect.Response[v1.QueryTelemetryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TelemetryService.QueryTelemetry is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) GetTelemetryStatus(context.Context, *connect.Request[v1.GetTelemetryStatusRequest]) (*connect.Response[v1.GetTelemetryStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TelemetryService.GetTelemetryStatus is not implemented"))
}
