// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: proto/mission/v1/mission.proto

package missionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissionTaskStatus int32

const (
	MissionTaskStatus_MISSION_TASK_STATUS_UNSPECIFIED MissionTaskStatus = 0
	MissionTaskStatus_MISSION_TASK_STATUS_ACCEPTED    MissionTaskStatus = 1
	MissionTaskStatus_MISSION_TASK_STATUS_IN_PROGRESS MissionTaskStatus = 2
	MissionTaskStatus_MISSION_TASK_STATUS_COMPLETED   MissionTaskStatus = 3
	MissionTaskStatus_MISSION_TASK_STATUS_FAILED      MissionTaskStatus = 4
)

// Enum value maps for MissionTaskStatus.
var (
	MissionTaskStatus_name = map[int32]string{
		0: "MISSION_TASK_STATUS_UNSPECIFIED",
		1: "MISSION_TASK_STATUS_ACCEPTED",
		2: "MISSION_TASK_STATUS_IN_PROGRESS",
		3: "MISSION_TASK_STATUS_COMPLETED",
		4: "MISSION_TASK_STATUS_FAILED",
	}
	MissionTaskStatus_value = map[string]int32{
		"MISSION_TASK_STATUS_UNSPECIFIED": 0,
		"MISSION_TASK_STATUS_ACCEPTED":    1,
		"MISSION_TASK_STATUS_IN_PROGRESS": 2,
		"MISSION_TASK_STATUS_COMPLETED":   3,
		"MISSION_TASK_STATUS_FAILED":      4,
	}
)

func (x MissionTaskStatus) Enum() *MissionTaskStatus {
	p := new(MissionTaskStatus)
	*p = x
	return p
}

func (x MissionTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mission_v1_mission_proto_enumTypes[0].Descriptor()
}

func (MissionTaskStatus) Type() protoreflect.EnumType {
	return &file_proto_mission_v1_mission_proto_enumTypes[0]
}

func (x MissionTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissionTaskStatus.Descriptor instead.
func (MissionTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{0}
}

type MissionClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MissionClientMessage_CreateTask
	//	*MissionClientMessage_AbortTask
	Payload       isMissionClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionClientMessage) Reset() {
	*x = MissionClientMessage{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionClientMessage) ProtoMessage() {}

func (x *MissionClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionClientMessage.ProtoReflect.Descriptor instead.
func (*MissionClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{0}
}

func (x *MissionClientMessage) GetPayload() isMissionClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MissionClientMessage) GetCreateTask() *CreateTask {
	if x != nil {
		if x, ok := x.Payload.(*MissionClientMessage_CreateTask); ok {
			return x.CreateTask
		}
	}
	return nil
}

func (x *MissionClientMessage) GetAbortTask() *AbortTask {
	if x != nil {
		if x, ok := x.Payload.(*MissionClientMessage_AbortTask); ok {
			return x.AbortTask
		}
	}
	return nil
}

type isMissionClientMessage_Payload interface {
	isMissionClientMessage_Payload()
}

type MissionClientMessage_CreateTask struct {
	CreateTask *CreateTask `protobuf:"bytes,1,opt,name=create_task,json=createTask,proto3,oneof"`
}

type MissionClientMessage_AbortTask struct {
	AbortTask *AbortTask `protobuf:"bytes,2,opt,name=abort_task,json=abortTask,proto3,oneof"`
}

func (*MissionClientMessage_CreateTask) isMissionClientMessage_Payload() {}

func (*MissionClientMessage_AbortTask) isMissionClientMessage_Payload() {}

type MissionServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MissionServerMessage_TaskStatusUpdate
	//	*MissionServerMessage_CreateTaskResponse
	Payload       isMissionServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionServerMessage) Reset() {
	*x = MissionServerMessage{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionServerMessage) ProtoMessage() {}

func (x *MissionServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionServerMessage.ProtoReflect.Descriptor instead.
func (*MissionServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{1}
}

func (x *MissionServerMessage) GetPayload() isMissionServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MissionServerMessage) GetTaskStatusUpdate() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*MissionServerMessage_TaskStatusUpdate); ok {
			return x.TaskStatusUpdate
		}
	}
	return nil
}

func (x *MissionServerMessage) GetCreateTaskResponse() *CreateTaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*MissionServerMessage_CreateTaskResponse); ok {
			return x.CreateTaskResponse
		}
	}
	return nil
}

type isMissionServerMessage_Payload interface {
	isMissionServerMessage_Payload()
}

type MissionServerMessage_TaskStatusUpdate struct {
	TaskStatusUpdate *TaskStatusUpdate `protobuf:"bytes,1,opt,name=task_status_update,json=taskStatusUpdate,proto3,oneof"`
}

type MissionServerMessage_CreateTaskResponse struct {
	CreateTaskResponse *CreateTaskResponse `protobuf:"bytes,2,opt,name=create_task_response,json=createTaskResponse,proto3,oneof"`
}

func (*MissionServerMessage_TaskStatusUpdate) isMissionServerMessage_Payload() {}

func (*MissionServerMessage_CreateTaskResponse) isMissionServerMessage_Payload() {}

type MissionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       []byte                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionContext) Reset() {
	*x = MissionContext{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionContext) ProtoMessage() {}

func (x *MissionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionContext.ProtoReflect.Descriptor instead.
func (*MissionContext) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{2}
}

func (x *MissionContext) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

type TaskContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // server generated task id
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // optional execution results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskContext) Reset() {
	*x = TaskContext{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContext) ProtoMessage() {}

func (x *TaskContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskContext.ProtoReflect.Descriptor instead.
func (*TaskContext) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{3}
}

func (x *TaskContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskContext) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type TaskRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // mission pins a specific agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequirements) Reset() {
	*x = TaskRequirements{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequirements) ProtoMessage() {}

func (x *TaskRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequirements.ProtoReflect.Descriptor instead.
func (*TaskRequirements) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{4}
}

func (x *TaskRequirements) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Client messages
type CreateTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task
	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // e.g. "GO_TO", "GO_HOME"
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // will match task schema payload
	// To be received back from the server during status update
	MissionContext *MissionContext `protobuf:"bytes,3,opt,name=mission_context,json=missionContext,proto3" json:"mission_context,omitempty"`
	// Requirements for the task to be executed, e.g. a specific agent or a specific robot type
	Requirement   *TaskRequirements `protobuf:"bytes,4,opt,name=requirement,proto3" json:"requirement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTask) Reset() {
	*x = CreateTask{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTask) ProtoMessage() {}

func (x *CreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTask.ProtoReflect.Descriptor instead.
func (*CreateTask) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTask) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateTask) GetMissionContext() *MissionContext {
	if x != nil {
		return x.MissionContext
	}
	return nil
}

func (x *CreateTask) GetRequirement() *TaskRequirements {
	if x != nil {
		return x.Requirement
	}
	return nil
}

type AbortTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTask) Reset() {
	*x = AbortTask{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTask) ProtoMessage() {}

func (x *AbortTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTask.ProtoReflect.Descriptor instead.
func (*AbortTask) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{6}
}

func (x *AbortTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// server messages
type CreateTaskResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissionContext *MissionContext        `protobuf:"bytes,1,opt,name=mission_context,json=missionContext,proto3" json:"mission_context,omitempty"`
	Status         MissionTaskStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mission.v1.MissionTaskStatus" json:"status,omitempty"`
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskResponse) GetMissionContext() *MissionContext {
	if x != nil {
		return x.MissionContext
	}
	return nil
}

func (x *CreateTaskResponse) GetStatus() MissionTaskStatus {
	if x != nil {
		return x.Status
	}
	return MissionTaskStatus_MISSION_TASK_STATUS_UNSPECIFIED
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissionContext *MissionContext        `protobuf:"bytes,1,opt,name=mission_context,json=missionContext,proto3" json:"mission_context,omitempty"`
	Status         MissionTaskStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mission.v1.MissionTaskStatus" json:"status,omitempty"`
	TaskContext    *TaskContext           `protobuf:"bytes,3,opt,name=task_context,json=taskContext,proto3" json:"task_context,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // optional message from the server
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_proto_mission_v1_mission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mission_v1_mission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_mission_v1_mission_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatusUpdate) GetMissionContext() *MissionContext {
	if x != nil {
		return x.MissionContext
	}
	return nil
}

func (x *TaskStatusUpdate) GetStatus() MissionTaskStatus {
	if x != nil {
		return x.Status
	}
	return MissionTaskStatus_MISSION_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetTaskContext() *TaskContext {
	if x != nil {
		return x.TaskContext
	}
	return nil
}

func (x *TaskStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mission_v1_mission_proto protoreflect.FileDescriptor

const file_proto_mission_v1_mission_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/mission/v1/mission.proto\x12\n" +
	"mission.v1\"\x94\x01\n" +
	"\x14MissionClientMessage\x129\n" +
	"\vcreate_task\x18\x01 \x01(\v2\x16.mission.v1.CreateTaskH\x00R\n" +
	"createTask\x126\n" +
	"\n" +
	"abort_task\x18\x02 \x01(\v2\x15.mission.v1.AbortTaskH\x00R\tabortTaskB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\x14MissionServerMessage\x12L\n" +
	"\x12task_status_update\x18\x01 \x01(\v2\x1c.mission.v1.TaskStatusUpdateH\x00R\x10taskStatusUpdate\x12R\n" +
	"\x14create_task_response\x18\x02 \x01(\v2\x1e.mission.v1.CreateTaskResponseH\x00R\x12createTaskResponseB\t\n" +
	"\apayload\"*\n" +
	"\x0eMissionContext\x12\x18\n" +
	"\acontext\x18\x01 \x01(\fR\acontext\"5\n" +
	"\vTaskContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\"-\n" +
	"\x10TaskRequirements\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xbf\x01\n" +
	"\n" +
	"CreateTask\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12C\n" +
	"\x0fmission_context\x18\x03 \x01(\v2\x1a.mission.v1.MissionContextR\x0emissionContext\x12>\n" +
	"\vrequirement\x18\x04 \x01(\v2\x1c.mission.v1.TaskRequirementsR\vrequirement\"$\n" +
	"\tAbortTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xa9\x01\n" +
	"\x12CreateTaskResponse\x12C\n" +
	"\x0fmission_context\x18\x01 \x01(\v2\x1a.mission.v1.MissionContextR\x0emissionContext\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.mission.v1.MissionTaskStatusR\x06status\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"\xe4\x01\n" +
	"\x10TaskStatusUpdate\x12C\n" +
	"\x0fmission_context\x18\x01 \x01(\v2\x1a.mission.v1.MissionContextR\x0emissionContext\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.mission.v1.MissionTaskStatusR\x06status\x12:\n" +
	"\ftask_context\x18\x03 \x01(\v2\x17.mission.v1.TaskContextR\vtaskContext\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*\xc2\x01\n" +
	"\x11MissionTaskStatus\x12#\n" +
	"\x1fMISSION_TASK_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMISSION_TASK_STATUS_ACCEPTED\x10\x01\x12#\n" +
	"\x1fMISSION_TASK_STATUS_IN_PROGRESS\x10\x02\x12!\n" +
	"\x1dMISSION_TASK_STATUS_COMPLETED\x10\x03\x12\x1e\n" +
	"\x1aMISSION_TASK_STATUS_FAILED\x10\x042i\n" +
	"\x0eMissionService\x12W\n" +
	"\rStreamMission\x12 .mission.v1.MissionClientMessage\x1a .mission.v1.MissionServerMessage(\x010\x01B+Z)vantageos-core/proto/mission/v1;missionv1b\x06proto3"

var (
	file_proto_mission_v1_mission_proto_rawDescOnce sync.Once
	file_proto_mission_v1_mission_proto_rawDescData []byte
)

func file_proto_mission_v1_mission_proto_rawDescGZIP() []byte {
	file_proto_mission_v1_mission_proto_rawDescOnce.Do(func() {
		file_proto_mission_v1_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mission_v1_mission_proto_rawDesc), len(file_proto_mission_v1_mission_proto_rawDesc)))
	})
	return file_proto_mission_v1_mission_proto_rawDescData
}

var file_proto_mission_v1_mission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mission_v1_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mission_v1_mission_proto_goTypes = []any{
	(MissionTaskStatus)(0),       // 0: mission.v1.MissionTaskStatus
	(*MissionClientMessage)(nil), // 1: mission.v1.MissionClientMessage
	(*MissionServerMessage)(nil), // 2: mission.v1.MissionServerMessage
	(*MissionContext)(nil),       // 3: mission.v1.MissionContext
	(*TaskContext)(nil),          // 4: mission.v1.TaskContext
	(*TaskRequirements)(nil),     // 5: mission.v1.TaskRequirements
	(*CreateTask)(nil),           // 6: mission.v1.CreateTask
	(*AbortTask)(nil),            // 7: mission.v1.AbortTask
	(*CreateTaskResponse)(nil),   // 8: mission.v1.CreateTaskResponse
	(*TaskStatusUpdate)(nil),     // 9: mission.v1.TaskStatusUpdate
}
var file_proto_mission_v1_mission_proto_depIdxs = []int32{
	6,  // 0: mission.v1.MissionClientMessage.create_task:type_name -> mission.v1.CreateTask
	7,  // 1: mission.v1.MissionClientMessage.abort_task:type_name -> mission.v1.AbortTask
	9,  // 2: mission.v1.MissionServerMessage.task_status_update:type_name -> mission.v1.TaskStatusUpdate
	8,  // 3: mission.v1.MissionServerMessage.create_task_response:type_name -> mission.v1.CreateTaskResponse
	3,  // 4: mission.v1.CreateTask.mission_context:type_name -> mission.v1.MissionContext
	5,  // 5: mission.v1.CreateTask.requirement:type_name -> mission.v1.TaskRequirements
	3,  // 6: mission.v1.CreateTaskResponse.mission_context:type_name -> mission.v1.MissionContext
	0,  // 7: mission.v1.CreateTaskResponse.status:type_name -> mission.v1.MissionTaskStatus
	3,  // 8: mission.v1.TaskStatusUpdate.mission_context:type_name -> mission.v1.MissionContext
	0,  // 9: mission.v1.TaskStatusUpdate.status:type_name -> mission.v1.MissionTaskStatus
	4,  // 10: mission.v1.TaskStatusUpdate.task_context:type_name -> mission.v1.TaskContext
	1,  // 11: mission.v1.MissionService.StreamMission:input_type -> mission.v1.MissionClientMessage
	2,  // 12: mission.v1.MissionService.StreamMission:output_type -> mission.v1.MissionServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_mission_v1_mission_proto_init() }
func file_proto_mission_v1_mission_proto_init() {
	if File_proto_mission_v1_mission_proto != nil {
		return
	}
	file_proto_mission_v1_mission_proto_msgTypes[0].OneofWrappers = []any{
		(*MissionClientMessage_CreateTask)(nil),
		(*MissionClientMessage_AbortTask)(nil),
	}
	file_proto_mission_v1_mission_proto_msgTypes[1].OneofWrappers = []any{
		(*MissionServerMessage_TaskStatusUpdate)(nil),
		(*MissionServerMessage_CreateTaskResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mission_v1_mission_proto_rawDesc), len(file_proto_mission_v1_mission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mission_v1_mission_proto_goTypes,
		DependencyIndexes: file_proto_mission_v1_mission_proto_depIdxs,
		EnumInfos:         file_proto_mission_v1_mission_proto_enumTypes,
		MessageInfos:      file_proto_mission_v1_mission_proto_msgTypes,
	}.Build()
	File_proto_mission_v1_mission_proto = out.File
	file_proto_mission_v1_mission_proto_goTypes = nil
	file_proto_mission_v1_mission_proto_depIdxs = nil
}
