// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: proto/mission/v1/mission.proto

package missionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MissionService_StreamMission_FullMethodName = "/mission.v1.MissionService/StreamMission"
)

// MissionServiceClient is the client API for MissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MissionServiceClient interface {
	StreamMission(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MissionClientMessage, MissionServerMessage], error)
}

type missionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMissionServiceClient(cc grpc.ClientConnInterface) MissionServiceClient {
	return &missionServiceClient{cc}
}

func (c *missionServiceClient) StreamMission(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MissionClientMessage, MissionServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MissionService_ServiceDesc.Streams[0], MissionService_StreamMission_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MissionClientMessage, MissionServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MissionService_StreamMissionClient = grpc.BidiStreamingClient[MissionClientMessage, MissionServerMessage]

// MissionServiceServer is the server API for MissionService service.
// All implementations must embed UnimplementedMissionServiceServer
// for forward compatibility.
type MissionServiceServer interface {
	StreamMission(grpc.BidiStreamingServer[MissionClientMessage, MissionServerMessage]) error
	mustEmbedUnimplementedMissionServiceServer()
}

// UnimplementedMissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMissionServiceServer struct{}

func (UnimplementedMissionServiceServer) StreamMission(grpc.BidiStreamingServer[MissionClientMessage, MissionServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMission not implemented")
}
func (UnimplementedMissionServiceServer) mustEmbedUnimplementedMissionServiceServer() {}
func (UnimplementedMissionServiceServer) testEmbeddedByValue()                        {}

// UnsafeMissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MissionServiceServer will
// result in compilation errors.
type UnsafeMissionServiceServer interface {
	mustEmbedUnimplementedMissionServiceServer()
}

func RegisterMissionServiceServer(s grpc.ServiceRegistrar, srv MissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedMissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MissionService_ServiceDesc, srv)
}

func _MissionService_StreamMission_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MissionServiceServer).StreamMission(&grpc.GenericServerStream[MissionClientMessage, MissionServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MissionService_StreamMissionServer = grpc.BidiStreamingServer[MissionClientMessage, MissionServerMessage]

// MissionService_ServiceDesc is the grpc.ServiceDesc for MissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mission.v1.MissionService",
	HandlerType: (*MissionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMission",
			Handler:       _MissionService_StreamMission_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mission/v1/mission.proto",
}
