// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: proto/api/v1/agent.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraType int32

const (
	CameraType_CAMERA_TYPE_UNSPECIFIED CameraType = 0
	CameraType_CAMERA_TYPE_MJPG        CameraType = 1
	CameraType_CAMERA_TYPE_RTSP        CameraType = 2
	CameraType_CAMERA_TYPE_WEBRTC      CameraType = 3
)

// Enum value maps for CameraType.
var (
	CameraType_name = map[int32]string{
		0: "CAMERA_TYPE_UNSPECIFIED",
		1: "CAMERA_TYPE_MJPG",
		2: "CAMERA_TYPE_RTSP",
		3: "CAMERA_TYPE_WEBRTC",
	}
	CameraType_value = map[string]int32{
		"CAMERA_TYPE_UNSPECIFIED": 0,
		"CAMERA_TYPE_MJPG":        1,
		"CAMERA_TYPE_RTSP":        2,
		"CAMERA_TYPE_WEBRTC":      3,
	}
)

func (x CameraType) Enum() *CameraType {
	p := new(CameraType)
	*p = x
	return p
}

func (x CameraType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CameraType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_agent_proto_enumTypes[0].Descriptor()
}

func (CameraType) Type() protoreflect.EnumType {
	return &file_proto_api_v1_agent_proto_enumTypes[0]
}

func (x CameraType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CameraType.Descriptor instead.
func (CameraType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AgentSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSkill) Reset() {
	*x = AgentSkill{}
	mi := &file_proto_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSkill) ProtoMessage() {}

func (x *AgentSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSkill.ProtoReflect.Descriptor instead.
func (*AgentSkill) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSkill) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Camera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Type          CameraType             `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.CameraType" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_proto_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Camera) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *Camera) GetType() CameraType {
	if x != nil {
		return x.Type
	}
	return CameraType_CAMERA_TYPE_UNSPECIFIED
}

func (x *Camera) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Skills        []*AgentSkill          `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	Cameras       []*Camera              `protobuf:"bytes,5,rep,name=cameras,proto3" json:"cameras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Agent) GetSkills() []*AgentSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Agent) GetCameras() []*Camera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_proto_api_v1_agent_proto protoreflect.FileDescriptor

const file_proto_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18proto/api/v1/agent.proto\x12\x06api.v1\x1a\x1cgoogle/protobuf/struct.proto\"S\n" +
	"\n" +
	"AgentSkill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"_\n" +
	"\x06Camera\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.api.v1.CameraTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x99\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12*\n" +
	"\x06skills\x18\x04 \x03(\v2\x12.api.v1.AgentSkillR\x06skills\x12(\n" +
	"\acameras\x18\x05 \x03(\v2\x0e.api.v1.CameraR\acameras\"\x13\n" +
	"\x11ListAgentsRequest\";\n" +
	"\x12ListAgentsResponse\x12%\n" +
	"\x06agents\x18\x01 \x03(\v2\r.api.v1.AgentR\x06agents*m\n" +
	"\n" +
	"CameraType\x12\x1b\n" +
	"\x17CAMERA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CAMERA_TYPE_MJPG\x10\x01\x12\x14\n" +
	"\x10CAMERA_TYPE_RTSP\x10\x02\x12\x16\n" +
	"\x12CAMERA_TYPE_WEBRTC\x10\x032S\n" +
	"\fAgentService\x12C\n" +
	"\n" +
	"ListAgents\x12\x19.api.v1.ListAgentsRequest\x1a\x1a.api.v1.ListAgentsResponseB#Z!vantageos-core/proto/api/v1;apiv1b\x06proto3"

var (
	file_proto_api_v1_agent_proto_rawDescOnce sync.Once
	file_proto_api_v1_agent_proto_rawDescData []byte
)

func file_proto_api_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_agent_proto_rawDesc), len(file_proto_api_v1_agent_proto_rawDesc)))
	})
	return file_proto_api_v1_agent_proto_rawDescData
}

var file_proto_api_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_api_v1_agent_proto_goTypes = []any{
	(CameraType)(0),            // 0: api.v1.CameraType
	(*AgentSkill)(nil),         // 1: api.v1.AgentSkill
	(*Camera)(nil),             // 2: api.v1.Camera
	(*Agent)(nil),              // 3: api.v1.Agent
	(*ListAgentsRequest)(nil),  // 4: api.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 5: api.v1.ListAgentsResponse
	(*structpb.Struct)(nil),    // 6: google.protobuf.Struct
}
var file_proto_api_v1_agent_proto_depIdxs = []int32{
	6, // 0: api.v1.AgentSkill.payload:type_name -> google.protobuf.Struct
	0, // 1: api.v1.Camera.type:type_name -> api.v1.CameraType
	1, // 2: api.v1.Agent.skills:type_name -> api.v1.AgentSkill
	2, // 3: api.v1.Agent.cameras:type_name -> api.v1.Camera
	3, // 4: api.v1.ListAgentsResponse.agents:type_name -> api.v1.Agent
	4, // 5: api.v1.AgentService.ListAgents:input_type -> api.v1.ListAgentsRequest
	5, // 6: api.v1.AgentService.ListAgents:output_type -> api.v1.ListAgentsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_api_v1_agent_proto_init() }
func file_proto_api_v1_agent_proto_init() {
	if File_proto_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_agent_proto_rawDesc), len(file_proto_api_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_api_v1_agent_proto = out.File
	file_proto_api_v1_agent_proto_goTypes = nil
	file_proto_api_v1_agent_proto_depIdxs = nil
}
