// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: proto/api/v1/mission.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissionStatus int32

const (
	MissionStatus_MISSION_STATUS_UNSPECIFIED MissionStatus = 0
	MissionStatus_MISSION_STATUS_PENDING     MissionStatus = 1
	MissionStatus_MISSION_STATUS_ACCEPTED    MissionStatus = 2
	MissionStatus_MISSION_STATUS_REJECTED    MissionStatus = 3
	MissionStatus_MISSION_STATUS_RUNNING     MissionStatus = 4
	MissionStatus_MISSION_STATUS_COMPLETED   MissionStatus = 5
	MissionStatus_MISSION_STATUS_FAILED      MissionStatus = 6
)

// Enum value maps for MissionStatus.
var (
	MissionStatus_name = map[int32]string{
		0: "MISSION_STATUS_UNSPECIFIED",
		1: "MISSION_STATUS_PENDING",
		2: "MISSION_STATUS_ACCEPTED",
		3: "MISSION_STATUS_REJECTED",
		4: "MISSION_STATUS_RUNNING",
		5: "MISSION_STATUS_COMPLETED",
		6: "MISSION_STATUS_FAILED",
	}
	MissionStatus_value = map[string]int32{
		"MISSION_STATUS_UNSPECIFIED": 0,
		"MISSION_STATUS_PENDING":     1,
		"MISSION_STATUS_ACCEPTED":    2,
		"MISSION_STATUS_REJECTED":    3,
		"MISSION_STATUS_RUNNING":     4,
		"MISSION_STATUS_COMPLETED":   5,
		"MISSION_STATUS_FAILED":      6,
	}
)

func (x MissionStatus) Enum() *MissionStatus {
	p := new(MissionStatus)
	*p = x
	return p
}

func (x MissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_mission_proto_enumTypes[0].Descriptor()
}

func (MissionStatus) Type() protoreflect.EnumType {
	return &file_proto_api_v1_mission_proto_enumTypes[0]
}

func (x MissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissionStatus.Descriptor instead.
func (MissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_mission_proto_rawDescGZIP(), []int{0}
}

type Mission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Status        MissionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=api.v1.MissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_proto_api_v1_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_mission_proto_rawDescGZIP(), []int{0}
}

func (x *Mission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mission) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Mission) GetStatus() MissionStatus {
	if x != nil {
		return x.Status
	}
	return MissionStatus_MISSION_STATUS_UNSPECIFIED
}

type ListMissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsRequest) Reset() {
	*x = ListMissionsRequest{}
	mi := &file_proto_api_v1_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsRequest) ProtoMessage() {}

func (x *ListMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsRequest.ProtoReflect.Descriptor instead.
func (*ListMissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_mission_proto_rawDescGZIP(), []int{1}
}

type ListMissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missions      []*Mission             `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsResponse) Reset() {
	*x = ListMissionsResponse{}
	mi := &file_proto_api_v1_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsResponse) ProtoMessage() {}

func (x *ListMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsResponse.ProtoReflect.Descriptor instead.
func (*ListMissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_mission_proto_rawDescGZIP(), []int{2}
}

func (x *ListMissionsResponse) GetMissions() []*Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

var File_proto_api_v1_mission_proto protoreflect.FileDescriptor

const file_proto_api_v1_mission_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/api/v1/mission.proto\x12\x06api.v1\"t\n" +
	"\aMission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.api.v1.MissionStatusR\x06status\"\x15\n" +
	"\x13ListMissionsRequest\"C\n" +
	"\x14ListMissionsResponse\x12+\n" +
	"\bmissions\x18\x01 \x03(\v2\x0f.api.v1.MissionR\bmissions*\xda\x01\n" +
	"\rMissionStatus\x12\x1e\n" +
	"\x1aMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MISSION_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17MISSION_STATUS_ACCEPTED\x10\x02\x12\x1b\n" +
	"\x17MISSION_STATUS_REJECTED\x10\x03\x12\x1a\n" +
	"\x16MISSION_STATUS_RUNNING\x10\x04\x12\x1c\n" +
	"\x18MISSION_STATUS_COMPLETED\x10\x05\x12\x19\n" +
	"\x15MISSION_STATUS_FAILED\x10\x062[\n" +
	"\x0eMissionService\x12I\n" +
	"\fListMissions\x12\x1b.api.v1.ListMissionsRequest\x1a\x1c.api.v1.ListMissionsResponseB#Z!vantageos-core/proto/api/v1;apiv1b\x06proto3"

var (
	file_proto_api_v1_mission_proto_rawDescOnce sync.Once
	file_proto_api_v1_mission_proto_rawDescData []byte
)

func file_proto_api_v1_mission_proto_rawDescGZIP() []byte {
	file_proto_api_v1_mission_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_mission_proto_rawDesc), len(file_proto_api_v1_mission_proto_rawDesc)))
	})
	return file_proto_api_v1_mission_proto_rawDescData
}

var file_proto_api_v1_mission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_v1_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_api_v1_mission_proto_goTypes = []any{
	(MissionStatus)(0),           // 0: api.v1.MissionStatus
	(*Mission)(nil),              // 1: api.v1.Mission
	(*ListMissionsRequest)(nil),  // 2: api.v1.ListMissionsRequest
	(*ListMissionsResponse)(nil), // 3: api.v1.ListMissionsResponse
}
var file_proto_api_v1_mission_proto_depIdxs = []int32{
	0, // 0: api.v1.Mission.status:type_name -> api.v1.MissionStatus
	1, // 1: api.v1.ListMissionsResponse.missions:type_name -> api.v1.Mission
	2, // 2: api.v1.MissionService.ListMissions:input_type -> api.v1.ListMissionsRequest
	3, // 3: api.v1.MissionService.ListMissions:output_type -> api.v1.ListMissionsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_api_v1_mission_proto_init() }
func file_proto_api_v1_mission_proto_init() {
	if File_proto_api_v1_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_mission_proto_rawDesc), len(file_proto_api_v1_mission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_mission_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_mission_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_mission_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_mission_proto_msgTypes,
	}.Build()
	File_proto_api_v1_mission_proto = out.File
	file_proto_api_v1_mission_proto_goTypes = nil
	file_proto_api_v1_mission_proto_depIdxs = nil
}
