// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: proto/api/v1/task.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED  TaskStatus = 0
	TaskStatus_TASK_STATUS_DRAFT        TaskStatus = 1
	TaskStatus_TASK_STATUS_STARTING     TaskStatus = 2
	TaskStatus_TASK_STATUS_CANNOT_START TaskStatus = 3
	TaskStatus_TASK_STATUS_STARTED      TaskStatus = 4
	TaskStatus_TASK_STATUS_EXPIRING     TaskStatus = 5
	TaskStatus_TASK_STATUS_EXPIRED      TaskStatus = 6
	TaskStatus_TASK_STATUS_ABORTING     TaskStatus = 7
	TaskStatus_TASK_STATUS_ABORTED      TaskStatus = 8
	TaskStatus_TASK_STATUS_FAILED       TaskStatus = 9
	TaskStatus_TASK_STATUS_FINISHING    TaskStatus = 10
	TaskStatus_TASK_STATUS_FINISHED     TaskStatus = 11
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0:  "TASK_STATUS_UNSPECIFIED",
		1:  "TASK_STATUS_DRAFT",
		2:  "TASK_STATUS_STARTING",
		3:  "TASK_STATUS_CANNOT_START",
		4:  "TASK_STATUS_STARTED",
		5:  "TASK_STATUS_EXPIRING",
		6:  "TASK_STATUS_EXPIRED",
		7:  "TASK_STATUS_ABORTING",
		8:  "TASK_STATUS_ABORTED",
		9:  "TASK_STATUS_FAILED",
		10: "TASK_STATUS_FINISHING",
		11: "TASK_STATUS_FINISHED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":  0,
		"TASK_STATUS_DRAFT":        1,
		"TASK_STATUS_STARTING":     2,
		"TASK_STATUS_CANNOT_START": 3,
		"TASK_STATUS_STARTED":      4,
		"TASK_STATUS_EXPIRING":     5,
		"TASK_STATUS_EXPIRED":      6,
		"TASK_STATUS_ABORTING":     7,
		"TASK_STATUS_ABORTED":      8,
		"TASK_STATUS_FAILED":       9,
		"TASK_STATUS_FINISHING":    10,
		"TASK_STATUS_FINISHED":     11,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_api_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type    string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g. "GO_TO", "GO_HOME"
	Payload *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Result  *structpb.Struct       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Status  TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=api.v1.TaskStatus" json:"status,omitempty"`
	// Mission linkage — both empty when task is standalone
	MissionId        string `protobuf:"bytes,7,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionContextId string `protobuf:"bytes,8,opt,name=mission_context_id,json=missionContextId,proto3" json:"mission_context_id,omitempty"`
	MissionContext   []byte `protobuf:"bytes,9,opt,name=mission_context,json=missionContext,proto3" json:"mission_context,omitempty"`
	// Lifecycle timestamps
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	ToExpireAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=to_expire_at,json=toExpireAt,proto3" json:"to_expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_api_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *Task) GetMissionContextId() string {
	if x != nil {
		return x.MissionContextId
	}
	return ""
}

func (x *Task) GetMissionContext() []byte {
	if x != nil {
		return x.MissionContext
	}
	return nil
}

func (x *Task) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *Task) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Task) GetToExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ToExpireAt
	}
	return nil
}

type CreateTaskRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional: task will be expired if not started within this time
	ToExpireAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to_expire_at,json=toExpireAt,proto3" json:"to_expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_api_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateTaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTaskRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateTaskRequest) GetToExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ToExpireAt
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_api_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FindTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTaskRequest) Reset() {
	*x = FindTaskRequest{}
	mi := &file_proto_api_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTaskRequest) ProtoMessage() {}

func (x *FindTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTaskRequest.ProtoReflect.Descriptor instead.
func (*FindTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *FindTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTaskResponse) Reset() {
	*x = FindTaskResponse{}
	mi := &file_proto_api_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTaskResponse) ProtoMessage() {}

func (x *FindTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTaskResponse.ProtoReflect.Descriptor instead.
func (*FindTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *FindTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_api_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_api_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_api_v1_task_proto protoreflect.FileDescriptor

const file_proto_api_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x17proto/api/v1/task.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfd\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06result\x12*\n" +
	"\x06status\x18\x06 \x01(\x0e2\x12.api.v1.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"mission_id\x18\a \x01(\tR\tmissionId\x12,\n" +
	"\x12mission_context_id\x18\b \x01(\tR\x10missionContextId\x12'\n" +
	"\x0fmission_context\x18\t \x01(\fR\x0emissionContext\x12;\n" +
	"\vreceived_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x125\n" +
	"\bstart_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x12<\n" +
	"\fto_expire_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"toExpireAt\"\xb3\x01\n" +
	"\x11CreateTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12<\n" +
	"\fto_expire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"toExpireAt\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"!\n" +
	"\x0fFindTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x10FindTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.api.v1.TaskR\x04task\"i\n" +
	"\x10ListTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"_\n" +
	"\x11ListTasksResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.api.v1.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\xc4\x02\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_STATUS_DRAFT\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_STARTING\x10\x02\x12\x1c\n" +
	"\x18TASK_STATUS_CANNOT_START\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_STARTED\x10\x04\x12\x18\n" +
	"\x14TASK_STATUS_EXPIRING\x10\x05\x12\x17\n" +
	"\x13TASK_STATUS_EXPIRED\x10\x06\x12\x18\n" +
	"\x14TASK_STATUS_ABORTING\x10\a\x12\x17\n" +
	"\x13TASK_STATUS_ABORTED\x10\b\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\t\x12\x19\n" +
	"\x15TASK_STATUS_FINISHING\x10\n" +
	"\x12\x18\n" +
	"\x14TASK_STATUS_FINISHED\x10\v2\xd3\x01\n" +
	"\vTaskService\x12C\n" +
	"\n" +
	"CreateTask\x12\x19.api.v1.CreateTaskRequest\x1a\x1a.api.v1.CreateTaskResponse\x12=\n" +
	"\bFindTask\x12\x17.api.v1.FindTaskRequest\x1a\x18.api.v1.FindTaskResponse\x12@\n" +
	"\tListTasks\x12\x18.api.v1.ListTasksRequest\x1a\x19.api.v1.ListTasksResponseB#Z!vantageos-core/proto/api/v1;apiv1b\x06proto3"

var (
	file_proto_api_v1_task_proto_rawDescOnce sync.Once
	file_proto_api_v1_task_proto_rawDescData []byte
)

func file_proto_api_v1_task_proto_rawDescGZIP() []byte {
	file_proto_api_v1_task_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_task_proto_rawDesc), len(file_proto_api_v1_task_proto_rawDesc)))
	})
	return file_proto_api_v1_task_proto_rawDescData
}

var file_proto_api_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_api_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: api.v1.TaskStatus
	(*Task)(nil),                  // 1: api.v1.Task
	(*CreateTaskRequest)(nil),     // 2: api.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 3: api.v1.CreateTaskResponse
	(*FindTaskRequest)(nil),       // 4: api.v1.FindTaskRequest
	(*FindTaskResponse)(nil),      // 5: api.v1.FindTaskResponse
	(*ListTasksRequest)(nil),      // 6: api.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 7: api.v1.ListTasksResponse
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_api_v1_task_proto_depIdxs = []int32{
	8,  // 0: api.v1.Task.payload:type_name -> google.protobuf.Struct
	8,  // 1: api.v1.Task.result:type_name -> google.protobuf.Struct
	0,  // 2: api.v1.Task.status:type_name -> api.v1.TaskStatus
	9,  // 3: api.v1.Task.received_at:type_name -> google.protobuf.Timestamp
	9,  // 4: api.v1.Task.start_at:type_name -> google.protobuf.Timestamp
	9,  // 5: api.v1.Task.to_expire_at:type_name -> google.protobuf.Timestamp
	8,  // 6: api.v1.CreateTaskRequest.payload:type_name -> google.protobuf.Struct
	9,  // 7: api.v1.CreateTaskRequest.to_expire_at:type_name -> google.protobuf.Timestamp
	1,  // 8: api.v1.FindTaskResponse.task:type_name -> api.v1.Task
	1,  // 9: api.v1.ListTasksResponse.tasks:type_name -> api.v1.Task
	2,  // 10: api.v1.TaskService.CreateTask:input_type -> api.v1.CreateTaskRequest
	4,  // 11: api.v1.TaskService.FindTask:input_type -> api.v1.FindTaskRequest
	6,  // 12: api.v1.TaskService.ListTasks:input_type -> api.v1.ListTasksRequest
	3,  // 13: api.v1.TaskService.CreateTask:output_type -> api.v1.CreateTaskResponse
	5,  // 14: api.v1.TaskService.FindTask:output_type -> api.v1.FindTaskResponse
	7,  // 15: api.v1.TaskService.ListTasks:output_type -> api.v1.ListTasksResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_api_v1_task_proto_init() }
func file_proto_api_v1_task_proto_init() {
	if File_proto_api_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_task_proto_rawDesc), len(file_proto_api_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_task_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_task_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_task_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_task_proto_msgTypes,
	}.Build()
	File_proto_api_v1_task_proto = out.File
	file_proto_api_v1_task_proto_goTypes = nil
	file_proto_api_v1_task_proto_depIdxs = nil
}
