// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/api/v1/telemetry.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPoint struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Time       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`                               // the mapped/event timestamp
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"` // broker receive time -- always present, a fallback ordering
	GroupId    string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`          // empty if the agent had no group at ingest time
	SchemaHash string                 `protobuf:"bytes,5,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"` // empty if there was no contract to validate against
	// valid is unset (nil) when there was no contract to validate against --
	// the no_contract case, see cmd/core/telemetry/store.Row.Valid.
	Valid         *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Fields        *structpb.Struct      `protobuf:"bytes,7,opt,name=fields,proto3" json:"fields,omitempty"`   // the mapped projection, if any
	Payload       *structpb.Struct      `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"` // the full raw payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPoint) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TelemetryPoint) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *TelemetryPoint) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TelemetryPoint) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *TelemetryPoint) GetValid() *wrapperspb.BoolValue {
	if x != nil {
		return x.Valid
	}
	return nil
}

func (x *TelemetryPoint) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TelemetryPoint) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QueryTelemetryRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	From    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// limit caps returned points; server-enforced hard ceiling applies
	// regardless (see cmd/core/controller/telemetry_connect.go).
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// bucket, e.g. "1m", "5m", "1h", downsamples via time_bucket at query
	// time instead of returning raw points -- see specs/mqtt_telemetry.specs.md
	// Step 13's reasoning: a day at 1Hz is 86k raw points, too many for a
	// browser chart to render usefully, let alone transfer cheaply.
	Bucket        string `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	PageToken     string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTelemetryRequest) Reset() {
	*x = QueryTelemetryRequest{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTelemetryRequest) ProtoMessage() {}

func (x *QueryTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTelemetryRequest.ProtoReflect.Descriptor instead.
func (*QueryTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *QueryTelemetryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *QueryTelemetryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryTelemetryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *QueryTelemetryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryTelemetryRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *QueryTelemetryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type QueryTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TelemetryPoint      `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTelemetryResponse) Reset() {
	*x = QueryTelemetryResponse{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTelemetryResponse) ProtoMessage() {}

func (x *QueryTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTelemetryResponse.ProtoReflect.Descriptor instead.
func (*QueryTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTelemetryResponse) GetPoints() []*TelemetryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *QueryTelemetryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetTelemetryStatusRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// window bounds the valid/invalid counts and recent violations below,
	// e.g. "1h", "24h". Defaults to 1h when empty.
	Window        string `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryStatusRequest) Reset() {
	*x = GetTelemetryStatusRequest{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryStatusRequest) ProtoMessage() {}

func (x *GetTelemetryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *GetTelemetryStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetTelemetryStatusRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type TelemetryViolationSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // validate.Kind, e.g. "missing_required"
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryViolationSummary) Reset() {
	*x = TelemetryViolationSummary{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryViolationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryViolationSummary) ProtoMessage() {}

func (x *TelemetryViolationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryViolationSummary.ProtoReflect.Descriptor instead.
func (*TelemetryViolationSummary) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryViolationSummary) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TelemetryViolationSummary) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *TelemetryViolationSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TelemetryViolationSummary) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetTelemetryStatusResponse struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	AgentId          string                       `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	GroupId          string                       `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SchemaHash       string                       `protobuf:"bytes,3,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`        // the group's current authoritative contract hash
	LastSeen         *timestamppb.Timestamp       `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`              // zero/unset if never seen
	ValidCount       int32                        `protobuf:"varint,5,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`       // over `window`
	InvalidCount     int32                        `protobuf:"varint,6,opt,name=invalid_count,json=invalidCount,proto3" json:"invalid_count,omitempty"` // over `window`
	RecentViolations []*TelemetryViolationSummary `protobuf:"bytes,7,rep,name=recent_violations,json=recentViolations,proto3" json:"recent_violations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTelemetryStatusResponse) Reset() {
	*x = GetTelemetryStatusResponse{}
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryStatusResponse) ProtoMessage() {}

func (x *GetTelemetryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *GetTelemetryStatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetTelemetryStatusResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetTelemetryStatusResponse) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *GetTelemetryStatusResponse) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *GetTelemetryStatusResponse) GetValidCount() int32 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *GetTelemetryStatusResponse) GetInvalidCount() int32 {
	if x != nil {
		return x.InvalidCount
	}
	return 0
}

func (x *GetTelemetryStatusResponse) GetRecentViolations() []*TelemetryViolationSummary {
	if x != nil {
		return x.RecentViolations
	}
	return nil
}

var File_proto_api_v1_telemetry_proto protoreflect.FileDescriptor

const file_proto_api_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/api/v1/telemetry.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xea\x02\n" +
	"\x0eTelemetryPoint\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x1f\n" +
	"\vschema_hash\x18\x05 \x01(\tR\n" +
	"schemaHash\x120\n" +
	"\x05valid\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x05valid\x12/\n" +
	"\x06fields\x18\a \x01(\v2\x17.google.protobuf.StructR\x06fields\x121\n" +
	"\apayload\x18\b \x01(\v2\x17.google.protobuf.StructR\apayload\"\xdb\x01\n" +
	"\x15QueryTelemetryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"p\n" +
	"\x16QueryTelemetryResponse\x12.\n" +
	"\x06points\x18\x01 \x03(\v2\x16.api.v1.TelemetryPointR\x06points\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x19GetTelemetryStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\"\x96\x01\n" +
	"\x19TelemetryViolationSummary\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xc2\x02\n" +
	"\x1aGetTelemetryStatusResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1f\n" +
	"\vschema_hash\x18\x03 \x01(\tR\n" +
	"schemaHash\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1f\n" +
	"\vvalid_count\x18\x05 \x01(\x05R\n" +
	"validCount\x12#\n" +
	"\rinvalid_count\x18\x06 \x01(\x05R\finvalidCount\x12N\n" +
	"\x11recent_violations\x18\a \x03(\v2!.api.v1.TelemetryViolationSummaryR\x10recentViolations2\xc0\x01\n" +
	"\x10TelemetryService\x12O\n" +
	"\x0eQueryTelemetry\x12\x1d.api.v1.QueryTelemetryRequest\x1a\x1e.api.v1.QueryTelemetryResponse\x12[\n" +
	"\x12GetTelemetryStatus\x12!.api.v1.GetTelemetryStatusRequest\x1a\".api.v1.GetTelemetryStatusResponseB#Z!vantageos-core/proto/api/v1;apiv1b\x06proto3"

var (
	file_proto_api_v1_telemetry_proto_rawDescOnce sync.Once
	file_proto_api_v1_telemetry_proto_rawDescData []byte
)

func file_proto_api_v1_telemetry_proto_rawDescGZIP() []byte {
	file_proto_api_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_telemetry_proto_rawDesc), len(file_proto_api_v1_telemetry_proto_rawDesc)))
	})
	return file_proto_api_v1_telemetry_proto_rawDescData
}

var file_proto_api_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_api_v1_telemetry_proto_goTypes = []any{
	(*TelemetryPoint)(nil),             // 0: api.v1.TelemetryPoint
	(*QueryTelemetryRequest)(nil),      // 1: api.v1.QueryTelemetryRequest
	(*QueryTelemetryResponse)(nil),     // 2: api.v1.QueryTelemetryResponse
	(*GetTelemetryStatusRequest)(nil),  // 3: api.v1.GetTelemetryStatusRequest
	(*TelemetryViolationSummary)(nil),  // 4: api.v1.TelemetryViolationSummary
	(*GetTelemetryStatusResponse)(nil), // 5: api.v1.GetTelemetryStatusResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),       // 7: google.protobuf.BoolValue
	(*structpb.Struct)(nil),            // 8: google.protobuf.Struct
}
var file_proto_api_v1_telemetry_proto_depIdxs = []int32{
	6,  // 0: api.v1.TelemetryPoint.time:type_name -> google.protobuf.Timestamp
	6,  // 1: api.v1.TelemetryPoint.received_at:type_name -> google.protobuf.Timestamp
	7,  // 2: api.v1.TelemetryPoint.valid:type_name -> google.protobuf.BoolValue
	8,  // 3: api.v1.TelemetryPoint.fields:type_name -> google.protobuf.Struct
	8,  // 4: api.v1.TelemetryPoint.payload:type_name -> google.protobuf.Struct
	6,  // 5: api.v1.QueryTelemetryRequest.from:type_name -> google.protobuf.Timestamp
	6,  // 6: api.v1.QueryTelemetryRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 7: api.v1.QueryTelemetryResponse.points:type_name -> api.v1.TelemetryPoint
	6,  // 8: api.v1.TelemetryViolationSummary.last_seen:type_name -> google.protobuf.Timestamp
	6,  // 9: api.v1.GetTelemetryStatusResponse.last_seen:type_name -> google.protobuf.Timestamp
	4,  // 10: api.v1.GetTelemetryStatusResponse.recent_violations:type_name -> api.v1.TelemetryViolationSummary
	1,  // 11: api.v1.TelemetryService.QueryTelemetry:input_type -> api.v1.QueryTelemetryRequest
	3,  // 12: api.v1.TelemetryService.GetTelemetryStatus:input_type -> api.v1.GetTelemetryStatusRequest
	2,  // 13: api.v1.TelemetryService.QueryTelemetry:output_type -> api.v1.QueryTelemetryResponse
	5,  // 14: api.v1.TelemetryService.GetTelemetryStatus:output_type -> api.v1.GetTelemetryStatusResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_api_v1_telemetry_proto_init() }
func file_proto_api_v1_telemetry_proto_init() {
	if File_proto_api_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_telemetry_proto_rawDesc), len(file_proto_api_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_api_v1_telemetry_proto_msgTypes,
	}.Build()
	File_proto_api_v1_telemetry_proto = out.File
	file_proto_api_v1_telemetry_proto_goTypes = nil
	file_proto_api_v1_telemetry_proto_depIdxs = nil
}
