// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_StreamTasks_FullMethodName         = "/agent.v1.AgentService/StreamTasks"
	AgentService_ReportTelemetry_FullMethodName     = "/agent.v1.AgentService/ReportTelemetry"
	AgentService_ReportPoseTelemetry_FullMethodName = "/agent.v1.AgentService/ReportPoseTelemetry"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC contract between core and agents.
type AgentServiceClient interface {
	// Core streams tasks down to the agent. It will also tell the core that
	// agent is alive or not.
	StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskAck, ServerMessage], error)
	// Agent streams telemetry up to core.
	ReportTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryAck], error)
	// Agent streams the pose telemetry up to core
	ReportPoseTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskAck, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskAck, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamTasksClient = grpc.BidiStreamingClient[TaskAck, ServerMessage]

func (c *agentServiceClient) ReportTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ReportTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryEvent, TelemetryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportTelemetryClient = grpc.ClientStreamingClient[TelemetryEvent, TelemetryAck]

func (c *agentServiceClient) ReportPoseTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_ReportPoseTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PoseTelemetryEvent, PoseTelemetryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportPoseTelemetryClient = grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC contract between core and agents.
type AgentServiceServer interface {
	// Core streams tasks down to the agent. It will also tell the core that
	// agent is alive or not.
	StreamTasks(grpc.BidiStreamingServer[TaskAck, ServerMessage]) error
	// Agent streams telemetry up to core.
	ReportTelemetry(grpc.ClientStreamingServer[TelemetryEvent, TelemetryAck]) error
	// Agent streams the pose telemetry up to core
	ReportPoseTelemetry(grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) StreamTasks(grpc.BidiStreamingServer[TaskAck, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTasks not implemented")
}
func (UnimplementedAgentServiceServer) ReportTelemetry(grpc.ClientStreamingServer[TelemetryEvent, TelemetryAck]) error {
	return status.Errorf(codes.Unimplemented, "method ReportTelemetry not implemented")
}
func (UnimplementedAgentServiceServer) ReportPoseTelemetry(grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]) error {
	return status.Errorf(codes.Unimplemented, "method ReportPoseTelemetry not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamTasks(&grpc.GenericServerStream[TaskAck, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamTasksServer = grpc.BidiStreamingServer[TaskAck, ServerMessage]

func _AgentService_ReportTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportTelemetry(&grpc.GenericServerStream[TelemetryEvent, TelemetryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportTelemetryServer = grpc.ClientStreamingServer[TelemetryEvent, TelemetryAck]

func _AgentService_ReportPoseTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportPoseTelemetry(&grpc.GenericServerStream[PoseTelemetryEvent, PoseTelemetryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportPoseTelemetryServer = grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTasks",
			Handler:       _AgentService_StreamTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportTelemetry",
			Handler:       _AgentService_ReportTelemetry_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportPoseTelemetry",
			Handler:       _AgentService_ReportPoseTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
