// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED  TaskStatus = 0
	TaskStatus_TASK_STATUS_DRAFT        TaskStatus = 1
	TaskStatus_TASK_STATUS_STARTING     TaskStatus = 2
	TaskStatus_TASK_STATUS_CANNOT_START TaskStatus = 3
	TaskStatus_TASK_STATUS_STARTED      TaskStatus = 4
	TaskStatus_TASK_STATUS_EXPIRING     TaskStatus = 5
	TaskStatus_TASK_STATUS_EXPIRED      TaskStatus = 6
	TaskStatus_TASK_STATUS_ABORTING     TaskStatus = 7
	TaskStatus_TASK_STATUS_ABORTED      TaskStatus = 8
	TaskStatus_TASK_STATUS_FAILED       TaskStatus = 9
	TaskStatus_TASK_STATUS_FINISHING    TaskStatus = 10
	TaskStatus_TASK_STATUS_FINISHED     TaskStatus = 11
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0:  "TASK_STATUS_UNSPECIFIED",
		1:  "TASK_STATUS_DRAFT",
		2:  "TASK_STATUS_STARTING",
		3:  "TASK_STATUS_CANNOT_START",
		4:  "TASK_STATUS_STARTED",
		5:  "TASK_STATUS_EXPIRING",
		6:  "TASK_STATUS_EXPIRED",
		7:  "TASK_STATUS_ABORTING",
		8:  "TASK_STATUS_ABORTED",
		9:  "TASK_STATUS_FAILED",
		10: "TASK_STATUS_FINISHING",
		11: "TASK_STATUS_FINISHED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":  0,
		"TASK_STATUS_DRAFT":        1,
		"TASK_STATUS_STARTING":     2,
		"TASK_STATUS_CANNOT_START": 3,
		"TASK_STATUS_STARTED":      4,
		"TASK_STATUS_EXPIRING":     5,
		"TASK_STATUS_EXPIRED":      6,
		"TASK_STATUS_ABORTING":     7,
		"TASK_STATUS_ABORTED":      8,
		"TASK_STATUS_FAILED":       9,
		"TASK_STATUS_FINISHING":    10,
		"TASK_STATUS_FINISHED":     11,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Task
	//	*ServerMessage_Abort
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetTask() *Task {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerMessage) GetAbort() *AbortCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Task struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type ServerMessage_Abort struct {
	Abort *AbortCommand `protobuf:"bytes,2,opt,name=abort,proto3,oneof"`
}

func (*ServerMessage_Task) isServerMessage_Payload() {}

func (*ServerMessage_Abort) isServerMessage_Payload() {}

type AbortCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortCommand) Reset() {
	*x = AbortCommand{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortCommand) ProtoMessage() {}

func (x *AbortCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortCommand.ProtoReflect.Descriptor instead.
func (*AbortCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AbortCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.TaskStatus" json:"status,omitempty"`       // robot sends: CANNOT_START, STARTED, ABORTED, FAILED, FINISHED
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // populated on FAILED
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                 // opaque result payload, populated on FINISHED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskAck) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type Task struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // e.g. "GO_TO", "GO_HOME"
	Payload []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // opaque task payload (matches current Task.Payload)
	// if the task is not executed within this time, it will be expired
	ToExpireAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to_expire_at,json=toExpireAt,proto3" json:"to_expire_at,omitempty"`
	// if the task is not completed within this time, it will be finalised
	ToFinaliseAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to_finalise_at,json=toFinaliseAt,proto3" json:"to_finalise_at,omitempty"`
	// The agent context contains information that can be used
	// by agent to pass message to other agents.
	// Please use with care, because it is not guaranteed to be available.
	AgentContext  *AgentContext `protobuf:"bytes,6,opt,name=agent_context,json=agentContext,proto3" json:"agent_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetToExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ToExpireAt
	}
	return nil
}

func (x *Task) GetToFinaliseAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ToFinaliseAt
	}
	return nil
}

func (x *Task) GetAgentContext() *AgentContext {
	if x != nil {
		return x.AgentContext
	}
	return nil
}

type AgentContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissionId      string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionContext string                 `protobuf:"bytes,2,opt,name=mission_context,json=missionContext,proto3" json:"mission_context,omitempty"`
	Context        []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentContext) Reset() {
	*x = AgentContext{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContext) ProtoMessage() {}

func (x *AgentContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContext.ProtoReflect.Descriptor instead.
func (*AgentContext) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentContext) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *AgentContext) GetMissionContext() string {
	if x != nil {
		return x.MissionContext
	}
	return ""
}

func (x *AgentContext) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // opaque telemetry payload (matches current raw bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

// Pose Telemetry
type PoseTelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LayoutId      string                 `protobuf:"bytes,2,opt,name=layout_id,json=layoutId,proto3" json:"layout_id,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Yaw           float64                `protobuf:"fixed64,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoseTelemetryEvent) Reset() {
	*x = PoseTelemetryEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoseTelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseTelemetryEvent) ProtoMessage() {}

func (x *PoseTelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseTelemetryEvent.ProtoReflect.Descriptor instead.
func (*PoseTelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PoseTelemetryEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PoseTelemetryEvent) GetLayoutId() string {
	if x != nil {
		return x.LayoutId
	}
	return ""
}

func (x *PoseTelemetryEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PoseTelemetryEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PoseTelemetryEvent) GetYaw() float64 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PoseTelemetryEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PoseTelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoseTelemetryAck) Reset() {
	*x = PoseTelemetryAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoseTelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseTelemetryAck) ProtoMessage() {}

func (x *PoseTelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseTelemetryAck.ProtoReflect.Descriptor instead.
func (*PoseTelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

// Heartbeat
type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatEvent) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatAck) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\rServerMessage\x12$\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.agent.v1.TaskH\x00R\x04task\x12.\n" +
	"\x05abort\x18\x02 \x01(\v2\x16.agent.v1.AbortCommandH\x00R\x05abortB\t\n" +
	"\apayload\"'\n" +
	"\fAbortCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x8d\x01\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.agent.v1.TaskStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\"\x81\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12<\n" +
	"\fto_expire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"toExpireAt\x12@\n" +
	"\x0eto_finalise_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ftoFinaliseAt\x12;\n" +
	"\ragent_context\x18\x06 \x01(\v2\x16.agent.v1.AgentContextR\fagentContext\"p\n" +
	"\fAgentContext\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12'\n" +
	"\x0fmission_context\x18\x02 \x01(\tR\x0emissionContext\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\"E\n" +
	"\x0eTelemetryEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x0e\n" +
	"\fTelemetryAck\"\xb4\x01\n" +
	"\x12PoseTelemetryEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tlayout_id\x18\x02 \x01(\tR\blayoutId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x01R\x03yaw\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x12\n" +
	"\x10PoseTelemetryAck\"E\n" +
	"\x0eHeartbeatEvent\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"C\n" +
	"\fHeartbeatAck\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt*\xc4\x02\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_STATUS_DRAFT\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_STARTING\x10\x02\x12\x1c\n" +
	"\x18TASK_STATUS_CANNOT_START\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_STARTED\x10\x04\x12\x18\n" +
	"\x14TASK_STATUS_EXPIRING\x10\x05\x12\x17\n" +
	"\x13TASK_STATUS_EXPIRED\x10\x06\x12\x18\n" +
	"\x14TASK_STATUS_ABORTING\x10\a\x12\x17\n" +
	"\x13TASK_STATUS_ABORTED\x10\b\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\t\x12\x19\n" +
	"\x15TASK_STATUS_FINISHING\x10\n" +
	"\x12\x18\n" +
	"\x14TASK_STATUS_FINISHED\x10\v2\xe7\x01\n" +
	"\fAgentService\x12=\n" +
	"\vStreamTasks\x12\x11.agent.v1.TaskAck\x1a\x17.agent.v1.ServerMessage(\x010\x01\x12E\n" +
	"\x0fReportTelemetry\x12\x18.agent.v1.TelemetryEvent\x1a\x16.agent.v1.TelemetryAck(\x01\x12Q\n" +
	"\x13ReportPoseTelemetry\x12\x1c.agent.v1.PoseTelemetryEvent\x1a\x1a.agent.v1.PoseTelemetryAck(\x01B*Z(vantageos-core/proto/agentsdk/v1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: agent.v1.TaskStatus
	(*ServerMessage)(nil),         // 1: agent.v1.ServerMessage
	(*AbortCommand)(nil),          // 2: agent.v1.AbortCommand
	(*TaskAck)(nil),               // 3: agent.v1.TaskAck
	(*Task)(nil),                  // 4: agent.v1.Task
	(*AgentContext)(nil),          // 5: agent.v1.AgentContext
	(*TelemetryEvent)(nil),        // 6: agent.v1.TelemetryEvent
	(*TelemetryAck)(nil),          // 7: agent.v1.TelemetryAck
	(*PoseTelemetryEvent)(nil),    // 8: agent.v1.PoseTelemetryEvent
	(*PoseTelemetryAck)(nil),      // 9: agent.v1.PoseTelemetryAck
	(*HeartbeatEvent)(nil),        // 10: agent.v1.HeartbeatEvent
	(*HeartbeatAck)(nil),          // 11: agent.v1.HeartbeatAck
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	4,  // 0: agent.v1.ServerMessage.task:type_name -> agent.v1.Task
	2,  // 1: agent.v1.ServerMessage.abort:type_name -> agent.v1.AbortCommand
	0,  // 2: agent.v1.TaskAck.status:type_name -> agent.v1.TaskStatus
	12, // 3: agent.v1.Task.to_expire_at:type_name -> google.protobuf.Timestamp
	12, // 4: agent.v1.Task.to_finalise_at:type_name -> google.protobuf.Timestamp
	5,  // 5: agent.v1.Task.agent_context:type_name -> agent.v1.AgentContext
	12, // 6: agent.v1.PoseTelemetryEvent.timestamp:type_name -> google.protobuf.Timestamp
	12, // 7: agent.v1.HeartbeatEvent.sent_at:type_name -> google.protobuf.Timestamp
	12, // 8: agent.v1.HeartbeatAck.sent_at:type_name -> google.protobuf.Timestamp
	3,  // 9: agent.v1.AgentService.StreamTasks:input_type -> agent.v1.TaskAck
	6,  // 10: agent.v1.AgentService.ReportTelemetry:input_type -> agent.v1.TelemetryEvent
	8,  // 11: agent.v1.AgentService.ReportPoseTelemetry:input_type -> agent.v1.PoseTelemetryEvent
	1,  // 12: agent.v1.AgentService.StreamTasks:output_type -> agent.v1.ServerMessage
	7,  // 13: agent.v1.AgentService.ReportTelemetry:output_type -> agent.v1.TelemetryAck
	9,  // 14: agent.v1.AgentService.ReportPoseTelemetry:output_type -> agent.v1.PoseTelemetryAck
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerMessage_Task)(nil),
		(*ServerMessage_Abort)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
