// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ReportPoseTelemetry_FullMethodName       = "/agent.v1.AgentService/ReportPoseTelemetry"
	AgentService_GetTransformationMatrices_FullMethodName = "/agent.v1.AgentService/GetTransformationMatrices"
	AgentService_ReportSkills_FullMethodName              = "/agent.v1.AgentService/ReportSkills"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC contract between core and agents. Task dispatch
// and telemetry ingest moved to MQTT (specs/mqtt_telemetry.specs.md Steps
// 16-17, StreamTasks/ReportTelemetry removed); pose streaming and the two
// RPCs below stay gRPC until Step 17's "pose and missions move" follow-up.
type AgentServiceClient interface {
	// Agent streams the pose telemetry up to core
	ReportPoseTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck], error)
	// Agent get the affine transformation matrix from core
	GetTransformationMatrices(ctx context.Context, in *TransformationMatrixRequest, opts ...grpc.CallOption) (*TransformationMatrixResponse, error)
	// agents send skills to core, so that core can know what skills the agent has
	ReportSkills(ctx context.Context, in *SkillRegistration, opts ...grpc.CallOption) (*SkillRegistrationAck, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ReportPoseTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportPoseTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PoseTelemetryEvent, PoseTelemetryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportPoseTelemetryClient = grpc.ClientStreamingClient[PoseTelemetryEvent, PoseTelemetryAck]

func (c *agentServiceClient) GetTransformationMatrices(ctx context.Context, in *TransformationMatrixRequest, opts ...grpc.CallOption) (*TransformationMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformationMatrixResponse)
	err := c.cc.Invoke(ctx, AgentService_GetTransformationMatrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportSkills(ctx context.Context, in *SkillRegistration, opts ...grpc.CallOption) (*SkillRegistrationAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillRegistrationAck)
	err := c.cc.Invoke(ctx, AgentService_ReportSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC contract between core and agents. Task dispatch
// and telemetry ingest moved to MQTT (specs/mqtt_telemetry.specs.md Steps
// 16-17, StreamTasks/ReportTelemetry removed); pose streaming and the two
// RPCs below stay gRPC until Step 17's "pose and missions move" follow-up.
type AgentServiceServer interface {
	// Agent streams the pose telemetry up to core
	ReportPoseTelemetry(grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]) error
	// Agent get the affine transformation matrix from core
	GetTransformationMatrices(context.Context, *TransformationMatrixRequest) (*TransformationMatrixResponse, error)
	// agents send skills to core, so that core can know what skills the agent has
	ReportSkills(context.Context, *SkillRegistration) (*SkillRegistrationAck, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ReportPoseTelemetry(grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]) error {
	return status.Error(codes.Unimplemented, "method ReportPoseTelemetry not implemented")
}
func (UnimplementedAgentServiceServer) GetTransformationMatrices(context.Context, *TransformationMatrixRequest) (*TransformationMatrixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransformationMatrices not implemented")
}
func (UnimplementedAgentServiceServer) ReportSkills(context.Context, *SkillRegistration) (*SkillRegistrationAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSkills not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ReportPoseTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportPoseTelemetry(&grpc.GenericServerStream[PoseTelemetryEvent, PoseTelemetryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportPoseTelemetryServer = grpc.ClientStreamingServer[PoseTelemetryEvent, PoseTelemetryAck]

func _AgentService_GetTransformationMatrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformationMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTransformationMatrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTransformationMatrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTransformationMatrices(ctx, req.(*TransformationMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportSkills(ctx, req.(*SkillRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransformationMatrices",
			Handler:    _AgentService_GetTransformationMatrices_Handler,
		},
		{
			MethodName: "ReportSkills",
			Handler:    _AgentService_ReportSkills_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportPoseTelemetry",
			Handler:       _AgentService_ReportPoseTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
