// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents": {
            "get": {
                "description": "Returns all provisioned agents, each annotated with whether it\ncurrently has a live gRPC stream, plus its reported skills and cameras.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "List agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.listAgentsResponse"
                        }
                    }
                }
            }
        },
        "/agents/register": {
            "post": {
                "description": "Called by a physical agentsdk on boot to register its identity and skills.\nThe request must include a pre-shared device API key as a Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Register an agentsdk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cdevice-api-key\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Agent registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agentsdk.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agentsdk.CameraConfig": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/agentsdk.CameraType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "agentsdk.CameraType": {
            "type": "string",
            "enum": [
                "mjpg",
                "rtsp",
                "webrtc"
            ],
            "x-enum-varnames": [
                "CameraTypeMJpg",
                "CameraTypeRtsp",
                "CameraTypeWebRtc"
            ]
        },
        "agentsdk.RegisterResponse": {
            "type": "object",
            "properties": {
                "grpc_addr": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "controller.agentView": {
            "type": "object",
            "properties": {
                "cameras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agentsdk.CameraConfig"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AgentSkill"
                    }
                }
            }
        },
        "controller.listAgentsResponse": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.agentView"
                    }
                }
            }
        },
        "controller.registerRequest": {
            "type": "object",
            "properties": {
                "cameras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agentsdk.CameraConfig"
                    }
                },
                "event_sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.EventSource"
                    }
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AgentSkill"
                    }
                }
            }
        },
        "model.AgentSkill": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "payload": {
                    "type": "object"
                }
            }
        },
        "model.EventSource": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "VantageOS Core API",
	Description:      "VantageOS backend — agentsdk registry and task management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
